name: fashion_ecommerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  advance_notification: ^1.0.6
  badges: ^3.1.1
  line_icons: ^2.0.1
  bottom_bar_matu: ^1.3.0
  pdfx: ^2.3.0
  internet_file: ^1.2.0
  file_picker: ^5.2.10
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1  
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  cell_calendar: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/    
    - assets/avon.pdf
    - assets/andrea.pdf
    - assets/betterware.pdf
    - assets/jafra.pdf
    - assets/marykay.pdf
    - assets/shelo.pdf
    - assets/concord.pdf

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf
          


 
